# HTTP-specific options.
http:

  # The port on which the HTTP server listens for service requests.
  port: 8080

  # The port on which the HTTP server listens for administrative requests.
  adminPort: 8081


# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:target/echo1

  properties:
      hibernate.show_sql: false
      hibernate.generate_statistics: false
      hibernate.use_sql_comments: false
      hibernate.hbm2ddl.auto: create

database2:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:target/echo2

  properties:
      hibernate.show_sql: false
      hibernate.generate_statistics: false
      hibernate.use_sql_comments: false
      hibernate.hbm2ddl.auto: create